-- Optional: Remove the table if you want to start fresh
-- DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS documents (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    title             text        NOT NULL,
    slug              text        NOT NULL UNIQUE,
    summary           text        NOT NULL DEFAULT '',

    body_text         text        NOT NULL DEFAULT '',
    content_format    text        NOT NULL DEFAULT 'markdown',  -- markdown | plain | html

    visibility        text        NOT NULL DEFAULT 'auth',      -- public | auth
    is_published      boolean     NOT NULL DEFAULT false,
    published_at      timestamptz NULL,

    original_filename text        NULL,
    mime_type         text        NULL,
    file_path         text        NULL,
    file_size_bytes   integer     NULL,

    created_by        text        NULL,                         -- FastAPI user, e.g. admin
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz NOT NULL DEFAULT now()
);