services:

  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    container_name: fastapi-edmuhlestein
    restart: unless-stopped
    expose:
      - "8000"                         # Internal port (no external exposure)
    networks:
      - ednet

networks:
  ednet:
    driver: bridge
