services:

  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    ports:
      - "8000:8000"   # Expose FastAPI directly to localhost:8000
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --log-level debug
    volumes:
      - ./fastapi/app:/app
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      DEBUG: true
    networks:
      - ednet
  
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - ednet

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: my-pgadmin
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_DEFAULT_EMAIL: emuhlestein@yahoo.com
      # Optional: skip master password prompt after login
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - ednet

volumes:
  db_data:
  pgadmin-data:

networks:
  ednet:
    driver: bridge